language: python

# Python 3.7 requires sudo in Travis.
# See: https://github.com/travis-ci/travis-ci/issues/9815
sudo: required
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
    - python: "3.8-dev"

install: pip install tox-travis tox

# Used by the `test` stage.
script: tox

stages:
  - test
  - lint
  - check-docs

jobs:
  include:

    # The `test` stage using the `python` matrix defined above
    # is included implicitly.

    - stage: lint
      name: "Code linting"
      python: "3.6"
      script: TOXENV=lint tox

    - stage: check-docs
      name: "Docs check"
      python: "3.6"
      script: TOXENV=check-docs tox
